name: "Sync GHAS to Jira"

on: 
  workflow_dispatch:
  #schedule:
    #- cron: '*/10 * * * *'    # trigger synchronization every 10 minutes

jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
      - name: Sync alerts to Jira issues
        uses: github/ghas-jira-integration@bidirectional_sync
        with:
          jira_url: 'https://githubtraining.atlassian.net'
          jira_user: '${{ secrets.JIRA_USER }}'
          jira_token: '${{ secrets.JIRA_TOKEN }}'
          jira_project: 'SEB'
          sync_direction: 'both'
